// Generated by CoffeeScript 1.3.3
var Cybozu, Event;

module.exports = Cybozu = (function() {

  function Cybozu(config) {
    this.config = config;
  }

  Cybozu.prototype.getEvents = function(callback) {
    return setTimeout(function() {
      return callback('佐藤');
    }, 10);
  };

  return Cybozu;

})();

Event = (function() {

  function Event(id) {
    this.id = id;
  }

  return Event;

})();
