// Generated by CoffeeScript 1.3.3
var BG, init, loginCallback, loginTest, resetOptions, restore, restoreOptions, save, saveAndClose, saveOptions;

save = function(id) {
  return localStorage[id] = document.getElementById(id).value;
};

restore = function(id) {
  return document.getElementById(id).value = localStorage[id];
};

init = function() {
  $('#version').text('version: ' + BG.version);
  if (localStorage["_init"] !== "_init") {
    localStorage["_init"] = "_init";
    localStorage["cybozuUrl"] = "";
    localStorage["_password"] = "";
    localStorage["_account"] = "";
    localStorage["serverCheckInterval"] = 30;
    localStorage["eventCheckInterval"] = 30;
    localStorage["eventBefore"] = 10;
    localStorage["closeAfter"] = 0;
  }
  return restoreOptions();
};

restoreOptions = function() {
  restore("_password");
  restore("_account");
  restore("cybozuUrl");
  restore("serverCheckInterval");
  restore("eventCheckInterval");
  restore("eventBefore");
  restore("closeAfter");
  return console.log("options restored.");
};

saveAndClose = function() {
  saveOptions();
  return chrome.tabs.getSelected(null, function(tab) {
    return chrome.tabs.remove(tab.id);
  });
};

saveOptions = function() {
  save("_password");
  save("_account");
  save("cybozuUrl");
  save("serverCheckInterval");
  save("eventCheckInterval");
  save("eventBefore");
  save("closeAfter");
  console.log("options saved");
  return BG.init();
};

resetOptions = function() {
  localStorage["_init"] = "";
  return init();
};

loginTest = function() {
  saveOptions();
  return BG.getEvents(loginCallback);
};

loginCallback = function(data) {
  return BG.notify(data);
};

BG = chrome.extension.getBackgroundPage();
