// Generated by CoffeeScript 1.3.3

$("a").each(function() {
  var ms, url;
  url = $(this).attr("href");
  if (!url) {
    return;
  }
  if (url.indexOf("/schedule/view") !== -1) {
    return $(this).attr("rel", url).cluetip({
      width: 500,
      showTitle: false,
      ajaxProcess: function(html) {
        var mainarea;
        mainarea = $("div.mainarea", html);
        return mainarea.html();
      }
    });
  } else if (url.indexOf("/user_view") !== -1) {
    if (url.indexOf("javascript") !== -1) {
      ms = url.match(/popupWin\(\'(.*)\',\'/);
      url = ms[1].replace("/grn/user_view", "/schedule/user_view");
    }
    console.log(url);
    return $(this).attr("rel", url).cluetip({
      width: 265,
      showTitle: false,
      ajaxProcess: function(html) {
        var img, mainarea, src, viewTable;
        mainarea = $("div.mainarea", html);
        viewTable = $("table.view_table", mainarea);
        img = $("img", viewTable)[0];
        src = "\"" + $(img).attr("src") + "\"";
        return "<img src=" + src + ">";
      }
    });
  }
});
